#!/usr/bin/env bash

set -e

cmd="$(tmux display -p '#{pane_current_command}')"
cmd="$(basename "${cmd,,*}")"
tmux resize-pane -Z
if [ "${cmd%m}" = "nvi" ]; then
  sleep 0.1
  tmux send-keys C-w =
fi
